# -*- coding: utf-8 -*-
"""JS02__Read_Netlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YbR10VOGgJ3zS87pAv6_JG-ROc8Qq-5b

# NOTE
- Drag and drop the extracted netlist (`extracted_netlist__2026_08_10.spice`) from PC
- Gemini convo for building the parser: See https://share.gemini.google/eWX3TkKSkHWL
Building the parser

# Basic parser for top level
We just want to examine the structure of the top-level block
"""

def parse_spice(spice_text):
    # Step 1: Join continuation lines ('+') and strip empty/comment lines
    raw_lines = spice_text.splitlines()
    joined_lines = []
    for line in raw_lines:
        line = line.strip()
        if not line or line.startswith("*"):
            continue
        if line.startswith("+"):
            if joined_lines:
                joined_lines[-1] += " " + line[1:].strip()
        else:
            joined_lines.append(line)

    # Step 2: Build the hierarchy tree
    tree = {"subckts": {}, "top_instances": []}
    current_subckt = None

    for line in joined_lines:
        tokens = line.split()
        cmd = tokens[0].lower()

        # Begin subcircuit definition
        if cmd == ".subckt":
            subckt_name = tokens[1]
            pins = tokens[2:]
            current_subckt = subckt_name
            tree["subckts"][subckt_name] = {"pins": pins, "instances": []}

        # End subcircuit definition
        elif cmd == ".ends":
            current_subckt = None

        # Component/Cell Instantiation (lines starting with X or M)
        elif tokens[0].upper().startswith(("X", "M")):
            inst_name = tokens[0]

            nets_and_cell = []
            params = {}

            # Separate pin connections/cell type from 'key=value' parameters
            for token in tokens[1:]:
                if "=" in token:
                    k, v = token.split("=", 1)
                    params[k] = v
                else:
                    nets_and_cell.append(token)

            # Last non-parameter token is the subckt/primitive type
            cell_type = nets_and_cell[-1] if nets_and_cell else None
            connections = nets_and_cell[:-1]

            inst_dict = {
                "name": inst_name.replace('sky130_fd_sc_hd__',''),
                "type": cell_type,
                "connections": connections,
                "params": params,
            }

            if current_subckt:
                tree["subckts"][current_subckt]["instances"].append(inst_dict)
            else:
                tree["top_instances"].append(inst_dict)

    return tree

'''
We just want the top level netlist of the 'puzzle' block
.subckt sky130_fd_sc_hd__or4bb_2 A X B D_N C_N VPWR VGND VPB VNB
'''
with open(r'extracted_netlist__2026_08_10.spice') as f:
    text = f.read()
    idx=text.find('.subckt puzzle')
    top_netlist = text[idx:]
tree = parse_spice(top_netlist)
cell_lookup = {cell_dict['name']:cell_dict for cell_dict in tree['subckts']['puzzle']['instances']}

"""Pick out just one instance"""

cell_lookup = {cell_dict['name']:cell_dict for cell_dict in tree['subckts']['puzzle']['instances']}

"""- Flat netlist: `puzzle` is flat (has no additional level of hierarchy beyind just the standard cells) with 942 cells (no subckts)
- There are 68 standard cell subckts used in building the `puzzle` top cell
- Leading X in cellname declarations: Declarations start with 'X' and all other mentions of the same cell in the netlist dont hav this leading 'X'. eg.
The declaration for this 9 fanout MUX is:
```
Xsky130_fd_sc_hd__mux2_1_9 sky130_fd_sc_hd__inv_2_7/A sky130_fd_sc_hd__mux2_1_9/A1
```
And all other mentions of this particular MUX go without the X
```
Xsky130_fd_sc_hd__mux2_1_16 sky130_fd_sc_hd__inv_2_7/A sky130_fd_sc_hd__mux2_1_9/A0 <---- here is our MUX!
```
(Maybe this leading X is a ngspice convention?...)

# Plan of attack
- The standard cells used have been dumped to a Google sheet.
- Provide the following to a LLM:
  - The (above) list of standard cells
  - URL to lookup what these cells do (eg. https://mithro-skywater.readthedocs.io/en/latest/contents/libraries/sky130_fd_sc_hd/cells/nor4/README.html)
  - LLM Output should be the verilog for these cells
"""

"""# Spice --> Verilog: Converting the instantiation lines to verilog

(First just convert and see, if we need to simulate it we need to add in the headers for standard cells from the sky130 repo)
"""

subckt_dict = {}
with open('subskts.csv', 'r') as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) >= 2 and parts[0].lower() == '.subckt':
            subckt_name = parts[1]
            # Parameters are all tokens after the subckt name
            parameters = parts[2:]
            subckt_dict[subckt_name] = parameters

verilog_lines = []
for k,v in subckt_dict.items():
  if k != 'puzzle':
      verilog_lines.append((f'`include "{k}.v"\n'))
verilog_lines += ["module puzzle (\ninput I,\noutput [7:0]O,\ninput clk,\ninput enable,\n input rst_n,\noutput success\n);"]
wires = []
groups = {}
for inst in tree['subckts']['puzzle']['instances']:
    cell_type = inst["type"]
    inst_name = inst["name"]
    pins = ", ".join(inst["connections"])
    pins_dict = {k: v for k, v in zip(subckt_dict[cell_type], pins.split())}

    #pins_dict = {k: v.replace('/','_') for k,v in pins_dict.items()}
    pins_dict = {k: v.replace(',','') for k,v in pins_dict.items()}
    pins_dict = {k: v for k,v in pins_dict.items() if k[0] != 'V'}
    pins_dict = {k: v.replace('sky130_fd_sc_hd__','') for k,v in pins_dict.items()}

    if len(list(pins_dict.values())) > 0:
      l = list(pins_dict.values())
      idx_ = [w.split('/')[0].split('_')[-1] for w in l]
     
      for v,w in zip(l,idx_):
        if w.isnumeric():
            v_ = v.split('/')
            v_ = "_".join(v_[0].split('_')[:-1]) + v_[-1]
            if v_ not in groups:
                groups[v_] = []
            groups[v_].append(int(w)) 
      pins_dict = {k: v.replace('/','_') for k,v in pins_dict.items()}
      #wires += ["_".join(w.split('/')[0].split('_')) for w in l]
      pins = ", ".join([f".{k}({v})\n" for k,v in pins_dict.items()])
      verilog_lines.append(f"  {cell_type} {inst_name} ({pins});\n")


groups = {k:sorted(list(set(v))) for k,v in groups.items()}
wires = list(set(wires))
wires = sorted(wires)

for w in wires:
    verilog_lines.append(f"wire {w};\n")

verilog_lines.append("endmodule")

f = open('puzzle3.v','w')
for v in verilog_lines:
  f.write(v)
